# Generated by Django 3.0.8 on 2020-07-23 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_auto_20200721_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionresuelta',
            name='evaluacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion_evaluaciones_resueltas', to='evaluaciones.Evaluacion'),
            preserve_default=False,
        ),
    ]
