# Generated by Django 3.0.8 on 2020-10-04 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='raw_password',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
