# Generated by Django 3.0.8 on 2020-10-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_raw_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.SmallIntegerField(choices=[(1, 'Administrador'), (2, 'Profesor'), (3, 'Estudiante'), (4, 'Publicador')]),
        ),
    ]
