# Generated by Django 3.0.8 on 2020-10-23 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201004_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tipo',
            field=models.SmallIntegerField(choices=[(1, 'Administrador'), (2, 'Profesor'), (3, 'Estudiante')]),
        ),
    ]
