# Generated by Django 4.1.3 on 2022-11-20 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='padres_representantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField(verbose_name=200)),
                ('apellidos', models.TextField(verbose_name=200)),
                ('dpi', models.TextField(verbose_name=12)),
                ('direccion', models.TextField(verbose_name=200)),
                ('telefono', models.TextField(verbose_name=8)),
                ('sexo', models.TextField(verbose_name=20)),
                ('estado_civil', models.TextField(verbose_name=60)),
            ],
        ),
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.TextField(verbose_name=200)),
                ('apellidos', models.TextField(verbose_name=200)),
                ('fecha_nacimiento', models.DateTimeField()),
                ('telefono', models.TextField(verbose_name=8)),
                ('direccion', models.TextField(verbose_name=200)),
                ('nacionalidad', models.TextField(verbose_name=200)),
                ('sexo', models.TextField(verbose_name=20)),
                ('partida_nacimiento', models.TextField(verbose_name=200)),
                ('padre_representantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_representante', to='inscripciones.padres_representantes')),
            ],
        ),
    ]
