# Generated by Django 4.1.3 on 2022-11-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inscripciones', '0002_padres_representantes_parentesco_alumno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumnos',
            name='apellidos',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='nacionalidad',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='nombres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='partida_nacimiento',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='sexo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='alumnos',
            name='telefono',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='padres_representantes',
            name='apellidos',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='padres_representantes',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='padres_representantes',
            name='dpi',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='padres_representantes',
            name='estado_civil',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='padres_representantes',
            name='nombres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='padres_representantes',
            name='parentesco_alumno',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='padres_representantes',
            name='sexo',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='padres_representantes',
            name='telefono',
            field=models.CharField(max_length=8),
        ),
    ]
