# Generated by Django 4.1.3 on 2022-11-24 04:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grado', '0001_initial'),
        ('inscripciones', '0003_alter_alumnos_apellidos_alter_alumnos_direccion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.CharField(max_length=4)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_asignado', to='inscripciones.alumnos')),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grado_asignado', to='grado.grado')),
            ],
        ),
    ]
