# Generated by Django 4.1.3 on 2022-11-25 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grado', '0006_delete_notas'),
        ('inscripciones', '0004_asignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=3)),
                ('ciclo', models.CharField(max_length=4)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno_nota', to='inscripciones.alumnos')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos_nota', to='grado.cursos')),
            ],
        ),
    ]
