# Generated by Django 4.1.3 on 2022-11-25 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grado', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='horario',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
    ]
