# Generated by Django 4.1.3 on 2022-11-25 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grado', '0002_cursos_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='nota_final',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
