# Generated by Django 4.1.3 on 2022-11-25 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grado', '0003_cursos_nota_final'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='nota_final',
        ),
    ]
