# Generated by Django 4.1.3 on 2022-11-25 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grado', '0004_remove_cursos_nota_final'),
    ]

    operations = [
        migrations.CreateModel(
            name='notas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.CharField(max_length=3)),
            ],
        ),
    ]
