# Generated by Django 4.1.3 on 2022-11-25 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grado', '0005_notas'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notas',
        ),
    ]
